# Generated by Django 4.1.1 on 2022-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_location_describe_alter_location_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
