# Generated by Django 4.1.1 on 2022-10-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_location_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='ward_commune',
            new_name='wardcommune',
        ),
    ]
