# Generated by Django 4.1.1 on 2022-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_ward_commune_location_wardcommune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/images/location/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/logo/location/%Y/%m/%d/'),
        ),
    ]
