# Generated by Django 4.1.1 on 2022-10-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_location_image_alter_location_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
