# Generated by Django 4.1.1 on 2022-11-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='location',
            new_name='detaillocation',
        ),
    ]
