# Generated by Django 4.1.1 on 2022-11-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='vote',
        ),
    ]
