# Generated by Django 4.1.1 on 2022-11-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_location_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
