# Generated by Django 4.1.1 on 2022-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_location_email_remove_location_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
