# Generated by Django 4.1.1 on 2022-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_images_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='describe',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
