# Generated by Django 4.1.1 on 2022-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_location_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
