# Generated by Django 4.1.1 on 2022-12-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_images_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
