# Generated by Django 4.1.1 on 2022-12-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_comment_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
