# Generated by Django 4.1.1 on 2022-12-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='timeend',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='timestart',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
