# Generated by Django 4.1.1 on 2022-12-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_location_timeend_alter_location_timestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='costmax',
            field=models.CharField(choices=[(50000, '50000'), (100000, '100000'), (120000, '120000'), (150000, '150000'), (200000, '200000'), (250000, '250000'), (300000, '300000')], max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='costmin',
            field=models.CharField(choices=[(25000, '25000'), (50000, '50000'), (100000, '100000'), (120000, '120000'), (150000, '150000'), (200000, '200000'), (250000, '250000')], max_length=10),
        ),
    ]
