# Generated by Django 4.1.1 on 2022-12-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_location_costmax_alter_location_costmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
