# Generated by Django 4.1.4 on 2022-12-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_visitor_visitorinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorinterest',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='VisitorInterest',
        ),
    ]
